#
## Application Properties
#

logger:
  level: debug
  request_format_in: ":date[iso] [IN] :method :url"
  request_format_out: ":date[iso] [OUT] :method :url status :status :response-time msec :res[content-length] bytes"

server:
  port: 5000
  public: "public"    # location of static resources